// <auto-generated />
using System;
using AccountManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountManager.Data.Migrations
{
    [DbContext(typeof(AccountManagerDbContext))]
    partial class AccountManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountManager.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountTypeId");

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            Code = "1.1",
                            Name = "Caja y Bancos"
                        },
                        new
                        {
                            Id = 2,
                            AccountTypeId = 1,
                            Code = "1.2",
                            Name = "Activo Circulante"
                        },
                        new
                        {
                            Id = 3,
                            AccountTypeId = 1,
                            Code = "1.3",
                            Name = "Efectivo"
                        },
                        new
                        {
                            Id = 4,
                            AccountTypeId = 1,
                            Code = "1.4",
                            Name = "Cuentas por Cobrar"
                        },
                        new
                        {
                            Id = 5,
                            AccountTypeId = 2,
                            Code = "2.1",
                            Name = "Pasivo y Capital"
                        },
                        new
                        {
                            Id = 6,
                            AccountTypeId = 2,
                            Code = "2.2",
                            Name = "Cuentas por Pagar"
                        },
                        new
                        {
                            Id = 7,
                            AccountTypeId = 2,
                            Code = "2.3",
                            Name = "Efectos por Pagar"
                        });
                });

            modelBuilder.Entity("AccountManager.Data.Models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("AccountType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1.",
                            Name = "Activos"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2.",
                            Name = "Pasivos"
                        });
                });

            modelBuilder.Entity("AccountManager.Data.Models.Account", b =>
                {
                    b.HasOne("AccountManager.Data.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
